name: Build RPCSX

on:
  push:
    paths-ignore:
      - "**/*.md"
      - '**/*.txt'
  pull_request:
    paths-ignore:
      - "**/*.md"
      - '**/*.txt'
  workflow_dispatch:

jobs:
  build-rpcsx:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Setup dependencies
      run: |
        sudo apt update
        sudo apt install build-essential libunwind-dev \
        libglfw3-dev libvulkan-dev vulkan-validationlayers-dev \
        spirv-tools glslang-tools libspirv-cross-c-shared-dev \
        libxbyak-dev
        
        VULKANVER=1.3.259
        curl -sL -o Vulkan-Headers.tar.gz https://github.com/KhronosGroup/Vulkan-Headers/archive/v${VULKANVER}.tar.gz
        tar -xf Vulkan-Headers*.tar.gz
        cd Vulkan-Headers*/ 
        mkdir build && cd build
        cmake ../ -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr
        ninja
        sudo ninja install

    - name: Build RPCSX
      run: |
        cmake -B build
        cmake --build build -j4

    - name: Upload RPCSX
      uses: actions/upload-artifact@v3
      with:
        name: rpcsx-bin
        path: build/bin/*
        if-no-files-found: error
